
def APP_NAME = 'config-server'

if (!env.BRANCH_NAME) {
    env.BRANCH_NAME = 'master'
}


StandardPipeline {
    node_label = 'java11'
    java_tool = 'JAVA_11'

    branchStrategy = new BranchStrategy().fxfStandardStrategy

    build_properties = [opts: '-DSPRING_PROFILES_ACTIVE=ci', tool: 'gradle', patterns: new Patterns().gradleJava, scmTagging: true, nexusTagging: false]
    fortify_id = "3531550_H3D-Config-Server"
    nexusIQ = [iqApplication: "config-server_3531550"]
    sonarqube = [autoBranchAnalysis: true, enforceQualityGate: true, ensureConfig: true, developerAdminAccess: true]
    EAI = '3531550'
    nexusCredentials = [id: 'NexusCredentials']
    discardBuilds = [maxNumberToKeep: 5]

}

