#!groovy
def APP_NAME = 'config-server'

if (!env.BRANCH_NAME) {
    env.BRANCH_NAME = 'master'
}


clearancePipline {
    node_label = 'java11'
    java_tool = 'JAVA_11'
    build_properties = [opts: '-DSPRING_PROFILES_ACTIVE=ci', tool: 'gradle', patterns: new Patterns().gradleJava, scmTagging: true, nexusTagging: false]
}

